nice_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: Mika2u7w
      dbname: stockdata
      schema: public
      port: 5432
      threads: 1
