version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mika2u7w
      POSTGRES_DB: stockdata
    ports:
      - "5432:5432"

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_users.xml:/etc/clickhouse-server/users.d/custom-users.xml:ro

  airflow-init:
    build: .
    image: airflow-custom
    depends_on:
      - postgres
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: Mika2u7w
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:Mika2u7w@postgres/stockdata
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ml:/opt/airflow/ml
      - ./dbt:/opt/dbt
    entrypoint: ["airflow", "db", "init"]

  airflow-webserver:
    build: .
    image: airflow-custom
    restart: always
    depends_on:
      - airflow-init
      - airflow-scheduler
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: Mika2u7w
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:Mika2u7w@postgres/stockdata
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: Mika2u7w
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ml:/opt/airflow/ml
      - ./dbt:/opt/dbt
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    image: airflow-custom
    restart: always
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: Mika2u7w
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:Mika2u7w@postgres/stockdata
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ml:/opt/airflow/ml
      - ./dbt:/opt/dbt
    command: scheduler

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.10
    environment:
      DBT_PROFILES_DIR: /opt/dbt
    volumes:
      - ./dbt:/opt/dbt
    depends_on:
      - postgres
    entrypoint: [ "sleep", "infinity" ]